### ISSUE TITLE
Incorrect building of mysql connection string with custom ports

### ISSUE THREAD

**Issue by CImrie** [imdrasil/jennifer.cr#121]
Problem: When specifying a custom port (like 3307), the connection string is decomposed and rebuilt without a semicolon separating the host and the port.

Effect: This causes a connection error. It tries to connect to `localhost3307:3306` because, by default in the mysql driver, it can not find a port from `localhost3307` connection string.

I have narrowed this down to `line 145` in `base.cr`.
It is fixed changing the line
from:
`host_part += Config.port.to_s if Config.port && Config.port > 0`
to:
`host_part += (":" + Config.port.to_s) if Config.port && Config.port > 0`

**Comment by imdrasil** [comment]
Yeah, you are right. This will be added to `0.5.1`

**Comment by imdrasil** [comment]
@CImrie please check out master branch

**Comment by CImrie** [comment]
I've checked this out and all seems fine. I think I've found another couple of issues so will post separately about those.

Thanks!
