### ISSUE TITLE
LHS of a Raw MySQL WHERE clause does not replace arguments

### ISSUE THREAD

**Issue by CImrie** [imdrasil/jennifer.cr#123]
When supplying a `WHERE` query that does not have a natural lhs/rhs (it is one statement), the whole condition is considered a LHS.

In `condition.cr` `Line 78-94`, the RHS is asked for `sql_args` but this is not performed on the LHS.
As a result, queries such as this fail to supply the proper arguments:
```mysql
SELECT regions.*
FROM regions
WHERE (ST_CONTAINS(ST_GeometryN(ST_GeomFromGeoJSON(regions.bounds, 1, 0), 1), POINT(?, ?)))
```

Example of the query being 'built':

```crystal
return Region.all.where {
  sql(
    "ST_CONTAINS(ST_GeometryN(ST_GeomFromGeoJSON(regions.bounds, 1, 0), 1), POINT(?, ?))",
    [point.longitude, point.latitude]
  )
}.to_a.first
```

The resulting error is:
```
Incorrect arguments to mysqld_stmt_execute.
Original query was:
SELECT regions.*
FROM regions
WHERE (ST_CONTAINS(ST_GeometryN(ST_GeomFromGeoJSON(regions.bounds, 1, 0), 1), POINT(?, ?)))

Jennifer::QueryBuilder::ModelQuery(Region+)@Jennifer::QueryBuilder::ModelQuery(T)#to_a:Array(Region+)
Region::find_point<Geo::Point>:Region+
```

**Comment by CImrie** [comment]
Do you have any thoughts on what the major pieces are that would need to be implemented to allow this? I'm happy to offer help.

I'm not sure what the purpose of the condition is for sql_args function - e.g:
```crystal
if filterable? && !(@operator == :is || @operator == :is_not)
          if @operator == :in || @operator == :between
```

Surely if the condition/criteria has any sql_args then they should be returned regardless of how they behave? Not just for specific rhs statements. 

I.e. I should be able to put `?` anywhere in an SQL statement and it should have an argument supplied for it.

**Comment by imdrasil** [comment]
Yeah, currently this is not supported - criteria behaves as solid piece of sql - column or raw sql. Some time before I had an idea to provide functionality to *register* sql functions to allow passing arguments instead of injecting them directly to query. But this may be overkill and useless thing. Maybe we really should think about allowing to pass arguments with raw sql.
Is this feature is very important for your project and blocks from moving forward?

**Comment by imdrasil** [comment]
@CImrie Please take a look on master branch - there is a fix for this case. Now you are able to do 
```crystal
Region.all.where {
  sql(
    "ST_CONTAINS(ST_GeometryN(ST_GeomFromGeoJSON(regions.bounds, 1, 0), 1), POINT(%s, %s))",
    [point.longitude, point.latitude]
  )
}.first
```

**Comment by CImrie** [comment]
@imdrasil Thanks very much for this - I was coping without it by injecting the data straight into the string (not best practice but fine since I controlled or trusted the source) - this will allow me to do it properly. I'll give it a try this evening and let you know 👍

**Comment by imdrasil** [comment]
@CImrie did you have a chance to play with fixed behavior?
