### ISSUE TITLE
Order Clauses do not compile when using real models/queries

### ISSUE THREAD

**Issue by CImrie** [imdrasil/jennifer.cr#124]
**Issue:**
`query._order.join(", ", io) { |(k, v), _| io.print k.as_sql(self), " ", v.upcase }` causes the following error:
```crystal
in lib/jennifer/src/jennifer/adapter/base_sql_generator.cr:202: undefined method 'upcase' for Nil (compile-time type is (String | Nil))

query._order.join(", ", io) { |(k, v), _| io.print k.as_sql(self), " ", v.upcase }
                                                                                  ^~~~~~
```

Every query is built by calling `self.body_section` in `base_sql_generator.cr`.
This calls `order_clause(io, query)` in the same file (`line 199-204`).

The following line (202) is the problematic one:
```crystal
query._order.join(", ", io) { |(k, v), _| io.print k.as_sql(self), " ", v.upcase }
```

**Explanation:**
`query._order` is a `CriteriaContainer`, which is an `Enumerable`.
The `Enumerable` class `join` method calls `each_with_index`, which uses `each` underneath.
`each` is overriden in `CriteraContainer` to use `@value_bucket[internal_key]` as the values for the iteration. _These are not guaranteed to be non-nil_.

This is **fixed by** changing the line to:
```crystal
query._order.join(", ", io) { |(k, v), _| io.print k.as_sql(self), " ", v.upcase unless v.nil? }
```

**Comment by CImrie** [comment]
Just found something interesting in `criteria_container.cr`, `Line 16-20`. By using `fetch` rather than `@value_bucket[internal_key]` syntax, the error disappears.
 
```crystal
      def each
        @key_bucket.each do |internal_key, criteria|
          yield({criteria, @value_bucket.fetch(internal_key)})
        end
      end
```

**Comment by imdrasil** [comment]
Yeah this one annoy me some time ago. I spent some time searching the root cause of such a behavior but unfortunately had no success. I guess ATM `#fetch` is the fastest and easiest way to resolve this one (ATM `v0.6.0` branch uses `#not_nil!` for this)

**Comment by CImrie** [comment]
Hey @imdrasil thanks again!
I'll check out v0.6.0 and take a look. Once I get more experience with Crystal in general I might reinvestigate this myself as it could be a bug in the Crystal compiler or in the Hash representation and nothing to do with Jennifer itself.

**Comment by imdrasil** [comment]
FYI: ATM `v0.6.0` is unstable and I wouldn't recommend to use it on production (and don't surprise if something doesn't work :smile: )
