### ISSUE TITLE
PG::Numeric Conversion

### ISSUE THREAD

**Issue by zauner** [imdrasil/jennifer.cr#128]
Hi,

the database I am using Jennifer with has most of its floating point values stored as `numeric`s. In order to make it work with Jennifer, I have to use `PG::Numeric` as type in the mapping. However, it would be convenient if it was possible to use e.g. `Float64`, to avoid having to use `to_f` constantly. Also using Postgres-specific data type in the application seems odd.

Is there already a way to deal with Numerics. I hacked around in the `_extract_attributes` method, with some success, but got the feeling ther could be a nicer solution.

Thanks for any help!

**Comment by imdrasil** [comment]
ATM to use numeric field you have to specify it `PG::Numeric`. Possible workaround may be specifying `after_initialize` callback with converting numeric field to float. But anyway this sounds reasonable - will try to add some way how to handle such a case in `0.6.0`.

**Comment by zauner** [comment]
Ok, I had to pursue this after all. Here's my workaround following your suggestion:

* Use `Union(PG::Numeric|Float64)` as type in the column mapping to satisfy the `res.read(...)` call
* Convert the field to `Float64` after initalize
* Add (override? not sure ...) the getter with a variant that returns `Float64`

```Crystal
class Product < Jennifer::Model::Base

  mapping({
    # [...]
    price: Union(PG::Numeric, Float64),
    # [...]
  })

  after_initialize :n2f
  def n2f
    @price = @price.to_f64.as(Float64)
  end

  def price : Float64
    @price.as(Float64)
  end
  
end
```

I packed it into a macro:

```Crystal
module ConvertNumerics

  macro convert_numerics(props)
    after_initialize :n2f
    def n2f
      {% for prop in props %}
        @{{prop}} = @{{prop}}.to_f64.as(Float64)
      {% end %}
    end

    {% for prop in props %}
      def {{prop.id}} : Float64
        @{{prop.id}}.as(Float64)
      end
    {% end %}
  end

end
```

to be able to use it like this in my models:

```Crystal
class Product < Jennifer::Model::Base
  include ConvertNumerics

  mapping({
    # [...]
    price: Union(PG::Numeric, Float64),
    # [...]
  })

  convert_numerics [price]
  
end
```

**Comment by zauner** [comment]
That's right. Couldn't find a painless way to create a PG::Numeric object, and so far my app is still read-only :)

But I guess the better solution would be anyway, to get rid of PG::Numeric _immediatly_ after reading from the database, and don't let it come as far as that getters/setters have to deal with it.

**Comment by zauner** [comment]
Also, Postgres' Numerics should rather be mapped to `BigDecimal` than to `Float64`, right?

**Comment by imdrasil** [comment]
Now on `v0.6.0` you can do

```crystal
class Product < Jennifer::Model::Base
  include ConvertNumerics

  mapping({
    # [...]
    price: { type: Float64, numeric_converter: :to_f64 },
    # [...]
  })
end
```

**Comment by zauner** [comment]
Cool, works great when reading from the DB!

However, when building an object from Hash like this

```Crystal
p = Product.build(
  # [...]
  price: 1000.0_f64
)
```
I am getting

`cast from Float64 to PG::Numeric failed`

I tracked it down to this location:
https://github.com/imdrasil/jennifer.cr/blob/2591344ec73e073b19724b9e38849499ab38882d/src/jennifer/model/mapping.cr#L327

and when removing the casts and conversions in that line like it was before, everything's fine:

`%var{key.id} = values[{{column}}]`

I think it makes sense. The value from the incoming Hash should be Float64 (or whatever you have in the mapping) anyway, right?

**Comment by imdrasil** [comment]
@zauner please clarify is this issue is resolved
