### ISSUE TITLE
Exception messages missing

### ISSUE THREAD

**Issue by taylorfinnell** [imdrasil/jennifer.cr#156]
For some reason whenever `BadQuery` is raised I don't see the exception message. The query is valid and works most of the time but raises an error every so often (possibly under load when number of connections is > than connection pool), any ideas or thoughts are appreciated. Here is the code that generates the query

```
      games = Game.where do
        sql("start_time >= $1 and start_time < $2 and country = $3", [time.at_beginning_of_day, time.at_end_of_day, country])
      end.to_a
```

Where `@time` is a valid `Time` object and `country` is a valid string

And here is the error, all I see a a `.` in the exception

```
2018-08-28T02:00:25.777683+00:00 app[web.1]: Exception: .
2018-08-28T02:00:25.777703+00:00 app[web.1]: Original query was:
2018-08-28T02:00:25.777706+00:00 app[web.1]: SELECT games.* FROM games WHERE (start_time >= $1 and start_time < $2 and country = $3)  | [2018-05-20 04:00:00.0 UTC, 2018-05-21 03:59:59.999999999 UTC, "us"] (Jennifer::BadQuery)
2018-08-28T02:00:25.777708+00:00 app[web.1]: from /tmp/build_39342a2f73a9345162c09702695125ed/lib/jennifer/src/jennifer/query_builder/model_query.cr:66:28 in '*Jennifer::QueryBuilder::ModelQuery(HqBuff::Game)' at 0x8573ee
```

Thank you! If I manage to reproduce it in a reduced way I will post more details, sorry to be vague :) 

EDIT: This is not in `--release` mode

**Comment by taylorfinnell** [comment]
Confirmed it's a pool thing. The actual error getting raised is DB::ConnectionRefused. Setting pool size to one fixes it, I don't understand why but it seems to

**Comment by imdrasil** [comment]
ATM I'm on vacation - will take a look in several days.

**Comment by taylorfinnell** [comment]
I think something is not releasing connections. I can watch the number of connections grow over the course of the day and never really drop. Even if there is no one using the website

**Comment by taylorfinnell** [comment]
Forgot to update this. The exception message missing is a bug here, which I just saw you made a PR for. The pool issue is probably this: https://github.com/crystal-lang/crystal-db/issues/77

**Comment by imdrasil** [comment]
Yeah - I've just wanted to post it. Related PR will just provide original error from the driver. ATM the only way to resolve your issue is set `initial_pool_size = max_pool_size = max_idle_pool_size`

**Comment by imdrasil** [comment]
Now I believe any connection leak issues should be fixed.

**Comment by imdrasil** [comment]
I believe it is only related to the transaction because:

```crystal
begin
Jennifer::Adapter.adapter.with_connection { 1 / 0 }
rescue e
end

puts Jennifer::Adapter.adapter.db.pool.@available.size # displays that the connection was released
```
