### ISSUE TITLE
Lots of noise when generating docs

### ISSUE THREAD

**Issue by taylorfinnell** [imdrasil/jennifer.cr#163]
When you run `crystal docs` a bunch of Jennifer internal code makes it into the html. Here is a screenshot showing what I mean. 

https://imgur.com/a/hUGYOkG

I think it's just a matter of adding `:nodoc:` on some of the internals

**Comment by imdrasil** [comment]
Agree. Will take a look

**Comment by imdrasil** [comment]
Hi @taylorfinnell . Take a look at the linked PR - I believe it removes all unnecessary documentation entries from the documentation.

**Comment by taylorfinnell** [comment]
Looks good to me!
