### ISSUE TITLE
Trouble with adding a migration

### ISSUE THREAD

**Issue by johansmitsnl** [imdrasil/jennifer.cr#166]
When adding a migration with a index I get a argument error. Running version `0.6.1`

`t.add_index(name: "nodes_uuid_index", field: :uuid, type: :uniq, order: :asc):`
```
instantiating 'Jennifer::Adapter::SchemaProcessor+#build_create_table(Tuple(Symbol), NamedTuple())'
in db/migrations/20180919214132979_node.cr:3: instantiating 'create_table(Symbol)'

   create_table(:nodes) do |t|
   ^~~~~~~~~~~~

in db/migrations/20180919214132979_node.cr:8: instantiating 'Jennifer::Migration::TableBuilder::CreateTable#add_index()'

        t.add_index(name: "nodes_uuid_index", field: :uuid, type: :uniq, order: :asc)
          ^~~~~~~~~

in lib/jennifer/src/jennifer/migration/table_builder/create_table.cr:59: instantiating 'index(Tuple(), NamedTuple(name: String, field: Symbol, type: Symbol, order: Symbol))'

          index(*args, **opts)
          ^~~~~

in lib/jennifer/src/jennifer/migration/table_builder/create_table.cr:48: instantiating 'index(String, Array(Symbol))'

          index(
          ^~~~~

in lib/jennifer/src/jennifer/migration/table_builder/create_table.cr:43: wrong number of arguments for 'Jennifer::Migration::TableBuilder::CreateIndex.new' (given 6, expected 7)
Overloads are:
 - Jennifer::Migration::TableBuilder::CreateIndex.new(adapter, table_name, index_name, fields, type, lengths, orders)

          @commands << CreateIndex.new(@name, name, fields, type, lengths, orders)
                                   ^~~
```

`t.add_index(name: "nodes_uuid_index", field: :uuid, type: :uniq, order: :asc, nil, nil):`
```
Error in sam.cr:3: while requiring "./db/migrations/*"

require "./db/migrations/*"
^

Syntax error in db/migrations/20180919214132979_node.cr:8: expected named argument, not nil

        t.add_index(name: "nodes_uuid_index", field: :uuid, type: :uniq, order: :asc, nil, nil)
                                                                                      ^
```

**Comment by imdrasil** [comment]
Hi. It may be because of `index(*args, **opts)` definition. Will take a look tomorrow. ATM try `t.add_index("nodes_uuid_index", :uuid, :uniq, order: :asc)` - this should work as expected

**Comment by johansmitsnl** [comment]
@imdrasil thanks, you suggested code did not work for me. I'll wait for the new update.

**Comment by imdrasil** [comment]
yeah. I will remove `#add_indec` method for `#create_table` in favor of `#index` - the first one is a bad (and useless) alias for the second one. So `t.index("nodes_uuid_index", :uuid, :uniq, order: :asc)` will work for sure now.

**Comment by johansmitsnl** [comment]
How can I test the code, when I do a shards update nothing is changed and also see no changes on the repo for the last 4 days.

**Comment by imdrasil** [comment]
Yesterday I had no time to push changes. Now master has all changes. Just run `shards update`. But be sure that you specified `branch: master` in your `shards.yml`. Feel free to reopen this issue if you face the same issue.
