### ISSUE TITLE
Question about STI

### ISSUE THREAD

**Issue by taylorfinnell** [imdrasil/jennifer.cr#199]
Is something like this supposed to work?

```

  class Foo < Jennifer::Model::Base
    mapping(
      ...,
      type: String
      ....
    )
  end

  class Bar < Foo
    mapping( ... )
  end

  class Baz < Foo
    mapping( ... )
  end

  Foo.all.to_a.each do |g|
    test(g)
  end

  def self.test(t : Bar)
    p "Bar"
  end

  def self.test(t : Baz)
    p "Baz"
  end
```

I get a no overload found for test(Foo+). Is it related to how covariance and contravariance works in Crystal?

**Comment by imdrasil** [comment]
It is supposed to work but you have to add one more method at the end

```crystal
def self.test(t : Foo)
  raise ArgumentError.new
end
```

Unfortunately I don't have deep enough knowledge to describe exact mechanism but in general you are right "Is it related to how covariance and contravariance works in Crystal".

**Comment by imdrasil** [comment]
@taylorfinnell did it help you?

**Comment by taylorfinnell** [comment]
Sorry for late response, it did not seem to help, the exception was just raised

**Comment by imdrasil** [comment]
@taylorfinnell did you have a chance to take at created branch?

**Comment by taylorfinnell** [comment]
Sometimes it works as expected sometimes (using code you gave above) it raises. I can't nail down specific cases though. For now I'm just using is_a?
