### ISSUE TITLE
Model mapping fails if datatype is Array

### ISSUE THREAD

**Issue by taylorfinnell** [imdrasil/jennifer.cr#208]
This is happening in the latest release. I think it as something to do with a property of one of my models being `Array(String)`

```
in lib/jennifer/src/jennifer/model/mapping.cr:49: undefined method 'union_types' for TypeNode of type Array(String) (must be a union type)

            {% if value[:type].is_a?(Generic) ? value[:type].resolve.union_types[0] == Bool : value[:type].resolve == Bool %}```

**Comment by taylorfinnell** [comment]
Yea, I removed all the `Array(String)` from my model mapping and it compiled fine

**Comment by imdrasil** [comment]
will take a look today

**Comment by imdrasil** [comment]
Hi, please clarify that created fix works for you. I'm doing to create a patch release on this week (including a fix for this issue and several small changes)

**Comment by taylorfinnell** [comment]
@imdrasil It works. Thanks!
