### ISSUE TITLE
"can't cast (TimePast | Nil) to String" when using `:converter`

### ISSUE THREAD

**Issue by grantspeelman** [imdrasil/jennifer.cr#220]
Thank you for this great shard, it has really been useful so far. I am hoping you can help me with the following issue I am having:

I am attempting to use the `:converter` for my own custom types, but running into the following issue:

```
expanding macro
in macro '__bool_convert' /app/lib/jennifer/src/jennifer/model/mapping.cr:5, line 2:

   1.         
>  2.           __temp_129.as(String)
   3.         
   4. 
```

Here is the code I wrote:
```crystal
class TimePast
  def self.cast(time_past : TimePast)
    time_past
  end

  def self.cast(time_past : String)
    TimePast.new(time_past)
  end

  def self.cast(value)
    TimePast.new(value.to_s)
  end

  def self.from_db(pull, nillable)
    cast(pull.read(String))
  end

  def self.to_db(value)
    value.to_s
  end

  def self.from_hash(hash : Hash, column)
    value = hash[column]
    cast(value)
  end

  def initialize(time_past : String)
    @time_past = time_past
  end
end

class Tracker < Jennifer::Model::Base
  mapping(
    id: Primary32,
    time_past: { type: String, converter: TimePast }
  )
end

describe Tracker do
  it do
    account = Tracker.build(time_past: "1 day")
    account.time_past.class.should eq(TimePast)
  end

  it do
    account = Tracker.build(time_past: "1 week")
    account.time_past.class.should eq(TimePast)
  end
end
```

Please let me know if I am missing something. Thank you

**Comment by imdrasil** [comment]
Current limitation is that `type` key presents column type and can be only one of `Jennifer::DBAny` alias subtype. As a result, class passed to `converter` key should also return one of `Jennifer::DBAny`.

As a workaround you can use

```crystal
class Tracker
  mapping(
    id: Primary32,
    time_past: String
  )

  setter passed_duration

  before_save :sync_time_past

  def passed_duration
    @passed_duration ||= TimePast.new(time_past)
  end

  private def sync_time_past
    self.time_past = passed_duration.time_past
  end
end
```

**Comment by imdrasil** [comment]
Is opportunity to define column with a custom class is crucial to you? Because before I thought that this is almost useless and can be done by workaround described above, but now I'm not so sure.

**Comment by grantspeelman** [comment]
thanks @imdrasil for the feedback, appreciate it.
I am still pretty new to crystal lang and I am really just experiment at the moment with Amber and different ORM's. 
Being able to use custom class is something i got use with Ruby on Rails attributes API and trying to find a ORM that can support something similar would be awesome. Helps with having less [Stringly Typed code](https://www.techopedia.com/definition/31876/stringly-typed) 😄 
I appreciate your feedback and thoughts
Thank you
