### ISSUE TITLE
question: abstract inheritance / override table name

### ISSUE THREAD

**Issue by sa-0001** [imdrasil/jennifer.cr#229]
can anyone tell me whether the following is possible at this time?

i would like to define an abstract model, which has columns, callbacks, and validations, but can not (or should not) be used directly.  then one or more concrete classes inherit from this, and specify a table name, additional columns, and override callbacks/validation.

(essentially, the same as `abstract_class` in ActiveRecord)

```
class AbstractModel < Jennifer::Model::Base
	mapping(
		id: Primary32,
	)
	
	before_update :before_update
	
	def before_update
		puts "parent before_update"
	end
end

class UserModel < AbstractModel
	table_name "users"
	
	mapping(
		name: String,
	)
	
	def before_update
		super
		puts "child before_update"
	end
end
```

this example will throw the exception _"You can't specify table name using STI on subclasses"_, but it could be that i just haven't found how to specify this correctly.

if it is not yet possible, then could this be considered a feature request?

**Comment by imdrasil** [comment]
Yes, ATM this use cast isn't supported - child table is considered as a child of STI. I guess this may be implemented in the next release (`0.8.0`). Will take a closer look after current pull request.

**Comment by sa-0001** [comment]
i found that there is a partial workaround for Granite by using a macro:

```
macro common_model
    primary id : Int32
    field whatever : String?
end

class CrUserModel < Granite::Base
    common_model
    
    table_name "users"
    
    field name_first : String?
    field name_last : String?
end
```

however for Jennifer, a duplicate `mapping` macro won't work, and the macro approach also doesn't allow you to use `super` in callbacks, only to override them completely.

**Comment by sa-0001** [comment]
yes, method overrides and super work with STI - i just meant that they do not work, when using a macro as a workaround for abstract inheritance.

**Comment by imdrasil** [comment]
start working on this
