### ISSUE TITLE
Question: any way to use a string type for a foreign key?

### ISSUE THREAD

**Issue by alex-min** [imdrasil/jennifer.cr#230]
I'm only using UUID for all the primary keys of all the tables, in Jennifer I use a String since it looks like I can't use the native UUID type, it does not compile. This currently works for using where & saving models, this part is ok.

However, I'm struggling to use the ```has_many``` relationship, I've tried all the combination possible but the query still expects an integer and raises a ```invalid input syntax for integer```, the ```foreign_type``` option does nothing.

I would like to do something like:

```crystal
class User < Jennifer::Model::Base
  ....
  has_many :messages, Message, foreign_type: String, foreign: :user_id
  ...
end
```

However that's does not seem enough to make it understand that user_id is a String and not an Int.

**Comment by imdrasil** [comment]
ATM drivers do not support `UUID` and just creates a `String` based on the value.

But It is pretty strange hearing about the issue with  because the following snippet works

```crystal
class Parent < Jennifer::Model::Base
  mapping(
    uuid: { type: String, primary: true }
  )
  
  has_many :children, Child, primary: :enn, foreign: :parent_enn
end

class Child < Jennifer::Model::Base
  mapping(
   id: Primary32,
   parent_enn: String
  )

  belongs_to :parent, Parent, primary: :enn, foreign: :parent_enn
end
```

Please provide some more detailed example that fails to figure out what is going wrong

**Comment by alex-min** [comment]
I've made some further tests and you are right, that does work but only from my test file. 
On the Amber app itself when live it does not work, even when I use the exact same model files as the test file, it's probably not the fault of jennifer then, I need to investigate more on why it happens, very strange issue...
