### ISSUE TITLE
Restrict result type of #exists? to Bool

### ISSUE THREAD

**Issue by skloibi** [imdrasil/jennifer.cr#241]
Hi,

I ran into a minor issue when using the `Executables#exists?` query method on Postgres.
As an example, when defining methods such as
```crystal
def contact_exists?(name) : Bool
  Contact.where { _name == name }.exists?
end
```
it results in a compile-time error:
```
type must be Bool, not (Array(PG::BoolArray) | Array(PG::CharArray) | Array(PG::Float32Array) | Array(PG::Float64Array) | Array(PG::Int16Array) | Array(PG::Int32Array) | Array(PG::Int64Array) | Array(PG::StringArray) | Bool | Char | Float32 | Float64 | Int16 | Int32 | Int64 | JSON::Any | PG::Geo::Box | PG::Geo::Circle | PG::Geo::Line | PG::Geo::LineSegment | PG::Geo::Path | PG::Geo::Point | PG::Geo::Polygon | PG::Numeric | Slice(UInt8) | String | Time | UInt32 | Nil)
```

Of course in this case the method is fairly trivial and would not require an explicit result type, but it would probably make sense for this method to be that restricted.
It seems to stem from the implementation of [`Jennifer::Postgres::Adapter#exists?`](https://github.com/imdrasil/jennifer.cr/blob/master/src/jennifer/adapter/postgres.cr#L212-L214) which may in theory return a result of any of the aforementioned types.

Could this be restricted to `Bool`? I don't think there is any case where *PostgreSQL* defines the result of `EXISTS` queries to be something else than that, right?

I already implemented this simple fix in a fork and will make a pull request if you say this is an issue: https://github.com/skloibi/jennifer.cr/tree/bug/restrict_exists_query_result_type

**Comment by imdrasil** [comment]
I agree - `#exists?` should return exact `Bool` value. I'd like to get a PR ) (but check also mysql adapter)
