### ISSUE TITLE
DB::ConnectionRefused exception with no error message

### ISSUE THREAD

**Issue by Hentioe** [imdrasil/jennifer.cr#254]
OS: Ubuntu 16.04
Jennifer Version: 0.7.1
Database Adapter: Sqlite3

A `DB::ConnectionRefused` exception occurred while calling the `create` or `create!` method, and there was no error message.
I don't know where the reason is now, my local (openSUSE) everything is fine. I have been debugging on the server for a long time.

Do you have any clues?😂

**Comment by imdrasil** [comment]
It's hard to say. It may be missing db file, database, user. This error means that at the driver level connection can't be established. It would be easier to determine a root cause if you give a minimum code to reproduce it (with db file location).

**Comment by Hentioe** [comment]
The reason I found it.

My DB file path configuration: `conf.db = "/data/dev.db"`, but Jennifer does not open the database file in the `/data` directory, but in the `$PWD/data/` directory Look for the database file.

Is this a BUG?

**Comment by imdrasil** [comment]
the reason is `db` is designed to specify file name. Use following configuration:
```crystal
Jennifer::Config.configure do |conf|
  # ...
  conf.host = "/data"
  conf.db = "dev.db"
  # ...
end
```

**Comment by imdrasil** [comment]
I will leave a notice in README about this

**Comment by Hentioe** [comment]
You answered my doubts perfectly, thank you.
