### ISSUE TITLE
Postgresql peer authentication failed for user "postgres"

### ISSUE THREAD

**Issue by lebogan** [imdrasil/jennifer.cr#256]
I am attempting to create a Kemal application using jennifer and sam - instead of granite and micrate - and I get the above error. I can, however, connect on the command line after creating the database `users_development`:
pg_hba.conf:
```
local  all  all  peer
host  all  all   127.0.0.1/32   md5
```
```
psql -U postgres -h localhost users_development
```
My `database.yml`:
```default: &default
  host: localhost
  user: postgres
  password: postgres
  adapter: postgres

development:
  <<: *default
  db: users_development
```
I even tried this in `database.cr`:
```
require "jennifer"
require "jennifer/adapter/postgres"

Jennifer::Config.configure do |conf|
  conf.host = "localhost"
  conf.user = "postgres"
  conf.password = "postgres"
  conf.adapter = "postgres"
  conf.db = "users_development"
  conf.migration_files_path = "./migrations"
  conf.logger.level = Logger::DEBUG
end
```
The commands I am using are `crystal sam.cr -- db:setup`, or `crystal sam.cr -- db:create`. The exact error message is: `DB command interface exit code 2: psql: FATAL: Peer authentication failed for user "postgres"`. I'm stumped.

**Comment by lebogan** [comment]
On further inspectioin: I changed the pg_hba.conf entry from peer to md5 and now I can create databases as the user postgres. This 'may' be due to the fact I'm on a vagrant-controlled virtualbox vm?

**Comment by imdrasil** [comment]
Hm, I'm not sure, but it may be. Also it may be some issue with crystal db adapter
