### ISSUE TITLE
Documentation in repository, linked from repo home

### ISSUE THREAD

**Issue by thomasnal** [imdrasil/jennifer.cr#26]
I love the documentation in this project much.  What I like about it much is that it is up-to-date according to the code.  When I used anything from the documentation it worked.

Currently the documentation is on wiki pages.

1) It is ideal to have a link to documentation on main README page.  "Read documentation index here." linked to a page with main topic and content.

2) Documentation is best maintained if it is associated with the actual version of the source code.  Wiki does not allow it, no clear how to create PR with improvements, ...  What I do is `docs/documentation_file.md` and make links from the README.md.  Then it is available for enhancements from contributors by the same process as improving the code.

**Comment by imdrasil** [comment]
About contributing - as far as I know this could be turned on in configurations (haven't do it in practice ever). But making separate `.md` files could be a nice idea as well. On the other hand this could be resolved via self-documentation and hosting docs as github pages

**Comment by thomasnal** [comment]
> haven't do it in practice ever)
That's what I mean :)  The easiest is to do it in a way most of us know by default - `.md` files and PRs.

> this could be resolved via self-documentation
The same long text still needs to be somewhere
- moved and reformatted to the source code
- or just copy and pasted to `.md` files (wiki content are just `.md` files) inside code repo without need to research and setup the process for github pages.

Options are out there, I just suggest a simple one unless there is an urge or a compelling reason to spent effort building, learning and maintaining something more elaborate.

Can be a nice PR.

**Comment by imdrasil** [comment]
@thomasnal , yeah, for now moving back to `.md` files will allow everyone easily participate in fixing some mistakes in the wiki or extend smth I've missed.

**Comment by thomasnal** [comment]
Very nice 👍 I will take time to test the other issue we talked about.  However, amber_cmd disappeared from github and my amber project doesn't compile.  Need to find a fix to it - no new anywhere.

**Comment by imdrasil** [comment]
For now all guides (I guess this word represents content better rather than "docs") could be found by this [link](https://imdrasil.github.io/jennifer.cr/). In future it will migrate to another repo and may change url
