### ISSUE TITLE
Requesting a new release

### ISSUE THREAD

**Issue by gdotdesign** [imdrasil/jennifer.cr#268]
Could you release the fix to the warnings please?

**Comment by imdrasil** [comment]
Hi. Totally forget that this change is just in master. I ging to make a release right after fix an issue with compiling ameba on travis (#269)

**Comment by imdrasil** [comment]
original blocker is described [here](https://travis-ci.community/t/fails-to-link-against-libgc-a-in-crystal-0-31-0/5197)

**Comment by gdotdesign** [comment]
Thanks!
