### ISSUE TITLE
Plans to support change in replacement of up/down?

### ISSUE THREAD

**Issue by norman784** [imdrasil/jennifer.cr#282]

**Comment by imdrasil** [comment]
In general all `TableBuilder`s are designed to be ready for further enhancement (like reversible operation) but ATM this feature doesn't have high priority.

**Comment by norman784** [comment]
Cool, thanks.

1- There's a Roadmap somewhere?
2- What other AR features are missing right now?

**Comment by imdrasil** [comment]
At the moment I have only notes what may be useful to be done. Later will create a separate issue with my thoughts about mission functionality and possible enhancements

**Comment by imdrasil** [comment]
Issue with the "roadmap" https://github.com/imdrasil/jennifer.cr/issues/285
