### ISSUE TITLE
Inability to run sam task until explicit Jennifer requirement

### ISSUE THREAD

**Issue by atatarenko** [imdrasil/jennifer.cr#283]
Hey,
I wasn't able to run `crystal sam.cr -- help` because of this issue
```crystal
In lib/jennifer/src/jennifer/sam.cr:6:5

 6 | Jennifer::Migration::Runner.migrate
```

I used CLI setup steps from [this](https://imdrasil.github.io/jennifer.cr/docs/getting_started) page and then got an error above. I basically added these lines two on the top of `sam.cr` file to make it work.
```crystal
# sam.cr
require "jennifer"
require "jennifer/adapter/postgres"

...

Sam.help
```

Probably, the setup steps should be updated.

**Comment by atatarenko** [comment]
Oh, I see there is [a page](https://imdrasil.github.io/jennifer.cr/docs/command_line) where it suggests to require the configuration file to `sam.cr`. So the example from the command line page can be just copied to the getting-started page.

**Comment by imdrasil** [comment]
Actually Getting started page has mention in the example `# here load jennifer and all required configurations`

**Comment by imdrasil** [comment]
adjusted doc in the scope of  #284

**Comment by atatarenko** [comment]
Thank you 👍
