### ISSUE TITLE
Conflicting mapping name is not properly resolved

### ISSUE THREAD

**Issue by skloibi** [imdrasil/jennifer.cr#288]
Hey there,

I've found a very specific issue if you define mapped structures with names that appear in the Jennifer standard library.
Specifically, compilation fails when defining a mapped class `OrderItem` as it at some point tries to resolve a generic type to `Jennifer::QueryBuilder::OrderItem`.
The following trace is the result:
```
In src/jennifer/query_builder/model_query.cr:47:54

 47 | @nested_relation_tree ||= NestedRelationTree.new(T)
                                                   ^--
Error: no overload matches 'Jennifer::QueryBuilder::NestedRelationTree.new' with type Jennifer::QueryBuilder::OrderItem.class
```

For comparison, it is enough to add the following class and use it somewhere to trigger this compilation issue:
```crystal
class OrderItem < Jennifer::Model::Base
  mapping(
    ...
  )
  ...
end
```
I know that this may easily be fixed on the user-side by renaming the target class, but since the error is a bit confusing at first sight, it may be worth looking into.

**Comment by skloibi** [comment]
Thanks a lot!

**Comment by imdrasil** [comment]
Now master has the fix for your issue
