### ISSUE TITLE
undefined constant Jennifer::Migration::Runner

### ISSUE THREAD

**Issue by sachinbhutani** [imdrasil/jennifer.cr#294]
I get the below error when trying to generate makefile for sam with 
$ crystal sam.cr -- generate:makefile 

sam version: 0.3.2
jennifer version: 0.8.4

```
In lib/jennifer/src/jennifer/sam.cr:6:5

 6 | Jennifer::Migration::Runner.migrate
     ^--------------------------
Error: undefined constant Jennifer::Migration::Runner
```
Sam.cr file contents: 
```
require "./db/migrations/*"
require "sam"

load_dependencies "jennifer"

Sam.help

```

**Comment by imdrasil** [comment]
As you can find [here](https://github.com/imdrasil/jennifer.cr/blob/master/docs/getting_started.md#cli) before requiring migrations and other stuff you should require Jennifer and all required configurations.

**Comment by imdrasil** [comment]
Did it work?

**Comment by sachinbhutani** [comment]
yes, it did! thanks.
