### ISSUE TITLE
Setters are not being called under certain circumstances

### ISSUE THREAD

**Issue by andrewc910** [imdrasil/jennifer.cr#308]
This is an issue I identified in granite-orm when making a PR for Amber. This issue is also in jennifer.

```crystal
class User < Jennifer::Model::Base
  JSON.mapping(
    email: {type: String?},
    password: {type: String?, setter: false},
  )
  mapping(
    email: {type: String},
    password_digest: {type: String?},
    password: {type: String?, virtual: true, setter: false}
  )

  def password=(password : String)
    @new_password = password
    self.password_digest = Crypto::Bcrypt::Password.create(password, cost: 10).to_s
  end
end

pp user = User.new({:email => "test@email.com", :password => "Password1234"})
#=> #<User:0x7fd0e02e31e0 email: "test@email.com", password_digest: nil, password: "Password123">
# Expected password_digest to not be nil

pp user = User.from_json({:email => "test@email.com", :password => "Password1234"}.to_json)
#=> #<User:0x7fd0e02e31e0 email: "test@email.com", password_digest: nil, password: "Password123">
# Expected password_digest to not be nil

user.password = "Password1234"
pp user
#=> #<User:0x7fd0e02e31e0 email: "andrew@email.com2", password_digest: "$2a$10$BulcHgGZv7rpDZoGvN8CXeww7F9fPoBAqvsEOyWeiRzTy0rKZT3JC", password: "Password123">
```

Is this is a bug or an expected outcome? When declaring custom setters, should I always invoke that setter explicitly like `user.password = x`?

**Comment by imdrasil** [comment]
The reason is that all instance variables should be initialized directly in the initializer. This definitely should be mentioned in the docs - will do. As a possible solution I could imaging that in initializer we assign all nilable variables to nil, or to default value if any, or to passed one and after that call setters on all variables with given arguments/default values/nils. But this will make everything more complicated

**Comment by imdrasil** [comment]
By the way, it might be useful to use [this shard](https://github.com/imdrasil/jennifer_twin) as an presenter-converter for the models to avoid polluting them with JSON mapping
