### ISSUE TITLE
Document or add feature for different classes to have separate database configurations (sharding)

### ISSUE THREAD

**Issue by didactic-drunk** [imdrasil/jennifer.cr#319]

**Comment by imdrasil** [comment]
Yep, `release/0.9.0` already has this functionality and documentation - you could have a look. The release will be done this weekend

**Comment by didactic-drunk** [comment]
I keep looking in `master`.

**Comment by didactic-drunk** [comment]
Is there a `release/0.9.0` for the sqlite adapter?

When using `0.9.0`:
```
 287 | abstract def command_interface
                    ^----------------
Error: abstract `def Jennifer::Adapter::Base#command_interface()` must be implemented by Jennifer::SQLite3::Adapter
```

**Comment by imdrasil** [comment]
No, there isn't. There isn't much work - I guess it also will be prepared and released during this weekend
