### ISSUE TITLE
Doesn't compile with Crystal 0.35.0

### ISSUE THREAD

**Issue by gaku-sei** [imdrasil/jennifer.cr#326]
The last release of Crystal introduces a breaking change for `CallStack`: https://github.com/crystal-lang/crystal/pull/9076

`lib/jennifer/src/jennifer/exceptions.cr` currently starts with:

```crystal
CallStack.skip(__FILE__)
```

It could be

```crystal
{% if compare_versions(Crystal::VERSION, "0.35.0") >= 0 %}
  Exception::CallStack.skip(__FILE__)
{% else %}
  CallStack.skip(__FILE__)
{% end %}
```

To preserve retro compatibilty and support Crystal > 0.35.0

**Comment by watzon** [comment]
Any progress? I was trying to use Jennifer and got this issue.

**Comment by imdrasil** [comment]
On a half o the way. The `master` branch will receive update in 1-2 days (approximately)

**Comment by imdrasil** [comment]
`master` got crystal 0.35.0 support. Next minor release will be done during this week - going to add 1 more feature. until that will keep open this issue to let others know about htis

**Comment by shootingfly** [comment]
@imdrasil Any progress?

**Comment by imdrasil** [comment]
Working on it - one thing should be implemented before bumping a new release. It seems I'll have some free time to get it done this week (closer to it end).

**Comment by imdrasil** [comment]
unfortunately still in progress :sob: - personal stuff takes all my free time. But I haven't forgotten about this

**Comment by imdrasil** [comment]
Apologies - totally forgot to come back here and say that everything works. Hope it didn't cause huge inconvenience :pensive:
