### ISSUE TITLE
Annotation friendly mapping

### ISSUE THREAD

**Issue by didactic-drunk** [imdrasil/jennifer.cr#332]
Is there a way to apply annotations to columns in jennifer or jennifer_twin without redeclaring all names and types?  I'm attempting to serialize with MessagePack but need custom conversion.

**Comment by imdrasil** [comment]
unfortunately no - in [jennifer twin](https://github.com/imdrasil/jennifer_twin) you need to redeclare fields to be able to specify annotation (see `age` field)

**Comment by didactic-drunk** [comment]
There must be a solution.  Something like:


```
macro column(name)
  @{{name}} : {{typeof(@model}}.@{{name}}
```

Or
```
mapping(Model,
  @[Experimental]
  age,

  @[Experimental]
  age {
    annotations: [
      "@[Experimental]",
    ]
  },

  * # map all remaining.
)
```

**Comment by didactic-drunk** [comment]
On my first model I have 1 field to override.  Perhaps the following API?

```
mapping_model Foo
column bar
mapping_auto?remaining?
```

```
mapping Foo, { bar...}
  calls mapping_model, column, map_remaining

**Comment by imdrasil** [comment]
with current crystal version it is possible - I remember that before there was an issue with setting annotation in macro from string. Will update jennifer_twin

**Comment by imdrasil** [comment]
`0.1.1` jennifer_twin got annotation support
