### ISSUE TITLE
Mapping column allow null but can't create because it can't be blank :|

### ISSUE THREAD

**Issue by huuhait** [imdrasil/jennifer.cr#334]
Hi i get some problem :| 

![image](https://user-images.githubusercontent.com/40519768/90394969-d5e1b080-e0bd-11ea-9679-b4a450ef5765.png)
![image](https://user-images.githubusercontent.com/40519768/90394952-cc584880-e0bd-11ea-94a9-789c95bfcd12.png)
![image](https://user-images.githubusercontent.com/40519768/90395053-0295c800-e0be-11ea-9cd6-bed251ba8d0e.png)

**Comment by imdrasil** [comment]
It seems you have validation set for `refferal_uid`. Also just DYI - it is enough to write `referral_uid: String?` to make it nullable

**Comment by huuhait** [comment]
> It seems you have validation set for `refferal_uid`. Also just DYI - it is enough to write `referral_uid: String?` to make it nullable

Yes i'm using validates_length for referral_uid.
Is there a way to allow null and validate?

**Comment by imdrasil** [comment]
Yeap, you can pass `allow_blank: true`. I guess this is missing in doc - will update it

**Comment by huuhait** [comment]
closed issue
