### ISSUE TITLE
table column validate with relation not work

### ISSUE THREAD

**Issue by huuhait** [imdrasil/jennifer.cr#335]
Hi i'm trying to validate a column with a relation but it always say NilAssertionError :|

**Comment by imdrasil** [comment]
Could you describe a bit more (also please include a code snippet)

**Comment by huuhait** [comment]
Hi @imdrasil 

here is my models

order.cr
`
require "uuid"

class Order < BaseModel
  table_name :orders
  with_timestamps

  class InsufficientMarketLiquidity < Exception
  end

  ZERO = 0.0
  STATES = { pending: 0, wait: 100, done: 200, cancel: -100, reject: -200 }

  PENDING = STATES["pending"]
  WAIT    = STATES["wait"]
  DONE    = STATES["done"]
  CANCEL  = STATES["cancel"]
  REJECT  = STATES["reject"]

  mapping(
    id:               Primary32,
    uuid:             String?,
    remote_id:        Int32?,
    bid:              String,
    market_id:        String,
    ask:              String,
    price:            Float64,
    volume:           Float64,
    origin_volume:    Float64,
    maker_fee:        { type: Float64, default: 0.0 },
    taker_fee:        { type: Float64, default: 0.0 },
    state:            Int32,
    type:             String,
    member_id:        Int32,
    ord_type:         String,
    locked:           { type: Float64, default: 0.0 },
    origin_locked:    { type: Float64, default: 0.0 },
    funds_received:   { type: Float64, default: 0.0 },
    trades_count:     { type: Int32, default: 0 },
    created_at:       Time?,
    updated_at:       Time?
  )

  belongs_to :market, Market
  belongs_to :member, Member
  belongs_to :ask_currency, Currency, foreign: :ask
  belongs_to :bid_currency, Currency, foreign: :bid

  validates_presence :ord_type
  validates_presence :volume
  validates_presence :origin_volume
  validates_presence :locked
  validates_presence :origin_locked
  validates_presence :price, if: is_limit_order?

  validates_numericality :price, greater_than: 0, if: ord_type == "limit"
  validates_numericality :price, greater_than_or_equal_to: market.not_nil!.min_price, if: is_limit_order?
  validates_numericality :origin_volume, greater_than: 0, greater_than_or_equal_to: market.not_nil!.min_amount

  validates_with_method :price_precision_validation, if: price.present?
  validates_with_method :origin_volume_precision_validation, if: origin_volume.present?
  validates_with_method :market_order_validations, if: ord_type == "market"

  scope :ordered { order(id: :asc) }
  scope :done { where(state: ::Order::DONE) }
  scope :active { where(state: ::Order::WAIT) }

  before_create :create_random_uuid
  after_validation :set_fee

  def create_random_uuid
    self.uuid = UUID.random.to_s
  end

  def set_fee
    return if self.maker_fee || self.taker_fee
    trading_fee = TradingFee.for(group: member.not_nil!.group, market_id: market_id)

    self.maker_fee = trading_fee.maker
    self.taker_fee = trading_fee.taker
  end

  def funds_used
    origin_locked - locked
  end

  def to_json
    {
      id:               id,
      uuid:             uuid,
      side:             side,
      ord_type:         ord_type,
      price:            price.to_s,
      avg_price:        avg_price.to_s,
      state:            state,
      market:           market_id,
      origin_volume:    origin_volume.to_s,
      remaining_volume: volume.to_s,
      executed_volume:  (origin_volume - volume).to_s,
      created_at:       created_at,
      updated_at:       updated_at,
      trades_count:     trades_count,
    }
  end

  def to_matching_attributes
    { id:        id,
      market:    market_id,
      type:      type[-3, 3].downcase,
      ord_type:  ord_type,
      volume:    volume.to_s,
      price:     price.to_s,
      locked:    locked.to_s,
      timestamp: created_at.to_unix.to_i }
  end

  def market_order_validations
    errors.add(:price, "must not be present") if price.present?
  end

  def price_precision_validation
    precision = market.not_nil!.price_precision

    unless price.round(precision) == price
      errors.add(:price, "precision must be less than or equal to #{precision}")
    end
  end

  def origin_volume_precision_validation
    precision = market.not_nil!.amount_precision

    unless origin_volume.round(precision) == origin_volume
      errors.add(:origin_volume, "precision must be less than or equal to #{precision}")
    end
  end

  def side
    type[-3, 3].downcase == "ask" ? "sell" : "buy"
  end

  def avg_price
  end

  def is_limit_order?
    ord_type == "limit"
  end
end
`

create a record:
`
    ::Order.new({
        state:              ::Order::PENDING,
        member:             current_user.not_nil!, // if i remove it validate with member not work (member is nil)
        member_id:          current_user.not_nil!.id,
        ask:                current_market.base_unit,
        bid:                current_market.quote_unit,
        market:             current_market.not_nil!, // if i remove it validate with market not work (market is nil)
        market_id:          current_market.id,
        type:               attrs.side == "sell" ? "OrderAsk" : "OrderBid",
        ord_type:           attrs.ord_type || "limit",
        price:              attrs.price,
        volume:             attrs.volume,
        origin_volume:      attrs.volume
      })
`

errors:
`cast from Member to (Array(Char) | Array(Float32) | Array(Float64) | Array(Int16) | Array(Int32) | Array(Int64) | Array(String) | Bool | Char | Float32 | Float64 | Int16 | Int32 | Int64 | Int8 | JSON::Any | PG::Geo::Box | PG::Geo::Circle | PG::Geo::Line | PG::Geo::LineSegment | PG::Geo::Path | PG::Geo::Point | PG::Geo::Polygon | PG::Numeric | Slice(UInt8) | String | Time | Time::Span | UInt32 | Nil) failed
`

**Comment by huuhait** [comment]
i've tested with query relation working good but i don't know why create a new record not working :|

**Comment by huuhait** [comment]
@imdrasil jennifer dont support it?

**Comment by imdrasil** [comment]
Hi, sorry for such a long response - too much happening around. Jennifer doesn't support passing relations to constructor (in your example `member` and `market` are relations not fields). You should pass ids only. For a record that already exists you can also use `#add_<relation name>` method like:

```crystal
order = Order.all.first!
order.add_member(member) # this persists foreign key to database immediately
```
