### ISSUE TITLE
Crystal Nightly: Error: cannot use 'in' as an argument name

### ISSUE THREAD

**Issue by mamantoha** [imdrasil/jennifer.cr#337]
```
In lib/jennifer/src/jennifer/validations/macros.cr:66:40

 66 | macro validates_inclusion(field, in, allow_blank = false, if if_value = nil)
                                       ^
Error: cannot use 'in' as an argument name
```

Reference: https://github.com/crystal-lang/crystal/pull/9704

This can be fixed by replacing `in` with something else. Suggestions?

**Comment by imdrasil** [comment]
We can try the same trick as with `if` argument: `macro validates_inclusion(field, in in_value ...)`
