### ISSUE TITLE
Support for UUID columns

### ISSUE THREAD

**Issue by huuhait** [imdrasil/jennifer.cr#341]
Hi.

i'm having some trouble in uuid key fields
can you add support it?

Type in mysq: varbinary(16)
Type in rails (mysql): t.binary

Sorry for now I only use mysql.

Thanks for your support

**Comment by imdrasil** [comment]
Hi, apologies - lost this issue from my radar. Native support of UUID is added in the latest versions of db drivers. Currently I'm not able to upgraded them because current versions of Amber and Lucky don't support them. I'll keep this open until it will be resolved

**Comment by imdrasil** [comment]
Close as `UUID` is supported
