### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by yujiri8** [imdrasil/jennifer.cr#343]
The page at https://imdrasil.github.io/jennifer.cr/docs/getting_started under heading "Setting up database connection" shows a database.cr with a typo: `jennifer::` instead of `Jennifer::` on line 7.

**Comment by yujiri8** [comment]
Oh also: it says `shards.yml` in the beginning, but that file needs to be called `shard.yml`.

**Comment by yujiri8** [comment]
(Not a typo, but it's also confusing how it says "If you want to use SQLite3 - add Jennifer SQLite3 adapter:", and then the next thing it says it that you *don't* need to add that explicitly.)

**Comment by imdrasil** [comment]
Thank you for finding this places :+1: . Going to address them tomorrow

**Comment by yujiri8** [comment]
Another typo: `has_many` is referred to as `mas_many` on the [relations](https://imdrasil.github.io/jennifer.cr/docs/relations) page.
