### ISSUE TITLE
Cannot filter relationships

### ISSUE THREAD

**Issue by yujiri8** [imdrasil/jennifer.cr#344]
I have models like:
```crystal
class Comment < Jennifer::Model::Base
  mapping(
    id: Primary64,
    name: String,
    body: String,
    article_path: String,
    article_title: String,
    time_added: Time,
    time_changed: Time?,
    user_id: Int64?,
  )
  belongs_to :user, User

class User < Jennifer::Model::Base
  mapping(
    id: Primary64,
    email: String,
    auth: String,
    name: String?,
    password: String?,
  )
  has_many :comments, Comment
end
```
So that `User.comments` refers to all the comments posted by a user. But it returns an `Array(Comment)` directly, so I can't use query building methods with it.

**Comment by zauner** [comment]
You also implicitly have `User.comments_query`. This is probably what you are looking for.

**Comment by yujiri8** [comment]
Oh, thank you! I missed that in the docs somehow. I will close this. Apologies for wasting your time.
