### ISSUE TITLE
Is there a way to create a default scope on a model?

### ISSUE THREAD

**Issue by jasonl99** [imdrasil/jennifer.cr#356]
I've got a table with a `deleted` column that means, for all intents and purposes, the record should not be retrieved (unless I explicitly want it).  Scopes work perfectly for this, but it means that every query needs it to be added.

My though would be something like `default_scope { where { deleted == false } }`.

**Comment by imdrasil** [comment]
currently this can be achieved by overriding `.all` method

```crystal
class Model < Jennifer::Mode::Base
  def self.all
    super.where { _deleted == false }
  end
end
```

This should be added to the docs

**Comment by jasonl99** [comment]
Awesome thank you!
