### ISSUE TITLE
Get problem with crystal 0.36.0

### ISSUE THREAD

**Issue by huuhait** [imdrasil/jennifer.cr#360]
![image](https://user-images.githubusercontent.com/40519768/106401771-76ebda00-6458-11eb-9565-934ea71a8d2c.png)

**Comment by imdrasil** [comment]
unfortunately even `0.36.1` isn't ready to be used so this issue have to wait until they fix all issues

**Comment by imdrasil** [comment]
Is unblocked - I missed one important update for abstract methods :disappointed:
