### ISSUE TITLE
Broken on crystal 1.1

### ISSUE THREAD

**Issue by didactic-drunk** [imdrasil/jennifer.cr#373]
`crystal spec`
```
In src/jennifer/adapter/base_sql_generator.cr:269:27

 269 | self.select(cte_query.as(QueryBuilder::ModelQuery))
                   ^
Error: can't cast Jennifer::QueryBuilder::ModelQuery(T) to Jennifer::QueryBuilder::ModelQuery(T)
```

This may be a crystal bug.

**Comment by imdrasil** [comment]
great :disappointed: . Thank you for catching this :+1: Will make this top priority and start investigating today

**Comment by imdrasil** [comment]
but on github I don't see official release for crystal 1.1.0. Did you install it from master branch?

**Comment by didactic-drunk** [comment]
master yes

**Comment by didactic-drunk** [comment]
This did it
```
commit e7b46c40739902db70a2dceebd09caf1a7c70553
Author: Quinton Miller <nicetas.c@gmail.com>
Date:   Tue Mar 30 17:21:14 2021 +0800

    Fix logic for subclass restricted against uninstantiated nested generic superclass (#10522)
```

**Comment by imdrasil** [comment]
Related issue was fixed in crystal repo. Thank you for your involvement :+1: Currently Jennifer with nightly crystal version is green. Will close this issue once merge my PR introducing nighlty crystal version check
