### ISSUE TITLE
Missing insert in adapter/mysql in V0.11.1

### ISSUE THREAD

**Issue by draco1006** [imdrasil/jennifer.cr#394]
I was trying Jennifer with Jennifer_sqlite3_adapter and i discover that the adapter defined in Jennifer_sqlite3_adapter.cr don't implement insert, and looking in the postgresql and mysql adapter if they have the method i discovered that it was missing in the adapter/mysql as well

**Comment by imdrasil** [comment]
Hi, sorry for such a long response. It is inherited from `Jennifer::Adapter::RequestMethods` module. Maybe describe what issue did you face so I'll be able to help you with it more efficiently?

**Comment by draco1006** [comment]
This is what happen following the documentation Getting started

![image](https://user-images.githubusercontent.com/50886668/146286394-416ebb17-418e-4914-b07d-000044f4f1d2.png)

**Comment by imdrasil** [comment]
yeap, that's because previous Jennifer version doesn't support crystal 1.2. Please install recently release version of both Jennifer (0.12.0) and sqlite3 adapter (0.4.0)
