### ISSUE TITLE
Change the type of `id` column of `migration_versions` to `bigint` via config?

### ISSUE THREAD

**Issue by cyangle** [imdrasil/jennifer.cr#398]
Cockroach DB only supports 64bit integer, currently it breaks the Jennifer db migrations because the ids are generated randomly and often exceed the 32bit integer range causing arithmetic overflow.

Is it possible to change `migration_versions`'s id column type dynamically via config?

**Comment by imdrasil** [comment]
Right now - no. In close future I want to switch default id column type and corresponding attribute type to int64. Until that you can monkeypatch `Jennifer::Adapter::Base` and `Jennifer::Migration::Runner` to use your custom `Migration` model. Other much more preferable solution is to extend mapping of existing `Version` model and modify it to use use int64 primary id. Unfortunately I'll be able to propose more precise solution only on Sunday/Monday
