### ISSUE TITLE
Initializing empty records with `Model.new` or `Model.build`

### ISSUE THREAD

**Issue by SebastianSzturo** [imdrasil/jennifer.cr#406]
Today Jennifer doesn't support `Model.new` or `Model.build` without any attributes nor with a sub-set of required attributes. Is this by choice or something that slipped through?

**Example:**
```crystal
class User < Jennifer::Model::Base
  with_timestamps

  mapping(
    id: Primary32,
    name: String,
    created_at: Time?,
    updated_at: Time?,
  )
end

User.new({:name => "Jennifer"})
Unhandled exception: Column User.age can't be casted from Nil to it's type - Int32 (Jennifer::DataTypeCasting)
  from src/models/user.cr:4:3 in '_extract_attributes'
  from src/models/user.cr:4:3 in 'initialize'
  from src/models/user.cr:4:3 in 'initialize'
  from src/models/user.cr:4:3 in 'new'
  from .icr_cRpmabygCPTixNpJwNqrZA.cr:13:3 in '__icr_exec__'
  from .icr_cRpmabygCPTixNpJwNqrZA.cr:16:26 in '__crystal_main'
  from /opt/homebrew/Cellar/crystal/1.3.2/src/crystal/main.cr:115:5 in 'main_user_code'
  from /opt/homebrew/Cellar/crystal/1.3.2/src/crystal/main.cr:101:7 in 'main'
  from /opt/homebrew/Cellar/crystal/1.3.2/src/crystal/main.cr:127:3 in 'main'


User.new
          ^--
Error: wrong number of arguments for 'User.new' (given 0, expected 1..2)

Overloads are:
 - User.new(values : Hash | NamedTuple, new_record : Bool)
 - User.new(values : Hash | NamedTuple, new_record)
 - User.new(pull : DB::ResultSet)
 - User.new(values : Hash(Symbol, AttrType) | NamedTuple)
 - User.new(values : Hash(String, AttrType))
```

**Comment by imdrasil** [comment]
Sorry for such  a long delay - finally I organized myself to have a regular time I can spend on open source projects again. Based on your example I can say:
- `Jennifer::Model::Mapping.mapping` generates a constructor with no parameters only if all fields are nillable or have default values
- in the 1st part of code snippet likely you have incomplete mapping as from the error message I see that `age` field is expected to be initialized

Does it make sense?

**Comment by cyangle** [comment]
@SebastianSzturo You can define mapping for a sub-set of table columns.
Check the doc https://imdrasil.github.io/jennifer.cr/docs/model_mapping

> If you don’t want to define all the table fields - pass false as second argument (this will disable default strict mapping mode).

So you should define the User model as below:
```
class User < Jennifer::Model::Base
  with_timestamps

  mapping(
    {
      id: Primary32,
      name: String,
      created_at: Time?,
      updated_at: Time?,
    },
    false
  )
end
```

**Comment by imdrasil** [comment]
@SebastianSzturo do you need any assistance with your issue?
