### ISSUE TITLE
Question about generators and authentication

### ISSUE THREAD

**Issue by crimson-knight** [imdrasil/jennifer.cr#411]
I saw in the docs that Jennifer has builtin authentication, however is there a generator that exists to create this model from a Sam command?

Something like: `crystal run sam.cr generate:authentication User`?

**Comment by imdrasil** [comment]
right now there is no generator for this

**Comment by imdrasil** [comment]
I don't think such kind of generator will bring some benefits as it is very easy to add it by hands. So I close this one
