### ISSUE TITLE
Warning: positional parameter 'pull'

### ISSUE THREAD

**Issue by crimson-knight** [imdrasil/jennifer.cr#412]
When running on Crystal 1.5, an error appears when running an app that uses Jennifer:
```bash
Warning: positional parameter 'pull' corresponds to parameter 'values' of the overridden method Jennifer::Model::Base::AbstractClassMethods#new(values : Hash | NamedTuple), which has a different name and may affect named argument passing
```

In addition to this, I see a message saying there are 10 other errors, however, the text is so long from the code output that I can't see the other errors.

**Comment by imdrasil** [comment]
Will take a look tomorrow :+1:

**Comment by crimson-knight** [comment]
No rush, it doesn't stop the shard from working. I started changing the positional param names to remove the warnings but I got worried that I'd be breaking some functionality if I did that.
