### ISSUE TITLE
Jennifer i18n conflict with amber 1.5

### ISSUE THREAD

**Issue by marvfinsy** [imdrasil/jennifer.cr#414]
Amber wants to use:  github: dare892/citrine-i18n. This conflicts with crimson-18n u use. Removing the amber one and using yours fails compile in a helper. The helper has a method that is trying access: "context.locale".

Also tried to use with Lucky framework. Jennifer seems  incompatible there also. u use a lower version of postgres "pg" adapter.

**Comment by imdrasil** [comment]
I'm working on upgrading to the latest `pg` version. Regarding `i18n` - will take look, thank you :+1:

**Comment by marvfinsy** [comment]
Looking in the amber issues board. There is a work-around described using an entry in the shard.override pointing to a version of the crimson-i18n that allows things to compile. That may give u some info.
https://github.com/amberframework/amber/issues/1288

There seems to also be some work in making Jennifer the default db in amber... (yeah)...

thx for response...

**Comment by imdrasil** [comment]
Now master can be used with the latest pg adapter. Regarding i18n - let's wait for amber to migrate.
