### ISSUE TITLE
feature request: EdgeDB support

### ISSUE THREAD

**Issue by notramo** [imdrasil/jennifer.cr#416]
EdgeDB is a relatively new, next-generation, object-graph database.
Could you add support for it, or is EdgeQL too much different from SQL? Maybe adding it at a higher level than SQL?
https://www.edgedb.com/

**Comment by imdrasil** [comment]
First of all we need to have a driver for this db like for [mysql](https://github.com/crystal-lang/crystal-mysql) or [postgres](https://github.com/will/crystal-pg). Having it we can start thinking on possible architecture for a Jennifer adapter.

**Comment by notramo** [comment]
@imdrasil What would bindings look like? EdgeDB works with objects instead of 2 dimensional tables, so it can be simply deserialized from JSON.
Also, it has a built-in migration tool which is much better than the solutions for MySQL/Postgres in Crystal.
However, a type-safe query builder would be cool. I do not know how much it could be integrated into this project, as, for example it doesn't need `JOIN` statements.

**Comment by imdrasil** [comment]
Before generating any king of requests we need to be able to communicate with EdgeDB server - send and receive data securely and effectively. For this purpose we need to have driver. This is outside of the scope of ActiveRecord pattern and this library.

**Comment by imdrasil** [comment]
Taking into account that there is no existing EdgeDB driver for crystal lang right now I close this ticket.
