### ISSUE TITLE
Error: expected argument #1 to 'Log#level=' to be Log::Severity, not Symbol

### ISSUE THREAD

**Issue by robacarp** [imdrasil/jennifer.cr#443]
I'm going through [your Getting Started docs](https://imdrasil.github.io/jennifer.cr/docs/getting_started#setting-up-database-connection) and after copying the database.cr initializer, I got this error message:

```crystal
In config/jennifer.cr:9:23

 9 | conf.logger.level = APP_ENV == "development" ? :debug : :error
                         ^
Error: expected argument #1 to 'Log#level=' to be Log::Severity, not Symbol

Overloads are:
 - Log#level=(value : Severity)
```

Lower down in the file it uses `Log.setup` correctly, so I just removed the line and it's fine.

**Comment by imdrasil** [comment]
Thank you  I'll update docs

**Comment by imdrasil** [comment]
In the next release Jennifer will promote using `Log.setup` instead of customer logger instance. It looks like this issue will be automatically resolved because of this. Please reopen this issue if I've missed anything here
