### ISSUE TITLE
Add colour to logs

### ISSUE THREAD

**Issue by wJoenn** [imdrasil/jennifer.cr#449]
I was kinda surprise to see the logger currently doesn't add colours to Jennifer's logs.
I cooked a little something to replace the `DBFormatter` and tried to make it as similar to Ruby's Active::Record's logger
```crystal
Jennifer::Config.configure do |config|
  formatter = Log::Formatter.new do |entry, io|
    io << "(#{entry.data[:time].as_f64.fdiv(1000).round(2)}ms)  ".colorize(:magenta)

    query = entry.data[:query].as_s
    color = case query.split.first
    when "DELETE" then :red
    when "INSERT" then :light_green
    when "SELECT" then :light_cyan
    when "UPDATE" then :yellow
    else :light_magenta
    end

    io << query.colorize(color)
    io << "  #{entry.data[:args]}" if entry.data[:args]? && !entry.data[:args].as_a.empty?
  end

  config.logger.backend = Log::IOBackend.new(formatter: formatter)
  # config.logger.backend = Log::IOBackend.new(formatter: Jennifer::Adapter::DBFormatter)
end
```

![image](https://github.com/imdrasil/jennifer.cr/assets/75388869/8c718ded-fd24-4d3d-b1da-57e3bbc317af)

Would you be interested in adding something similar in `DB::Formatter` ?
I can make try to make a PR if you don't have the time

**Comment by imdrasil** [comment]
Hi. Now master branch has new colorized log formatter. Does it cover your use-case?

**Comment by wJoenn** [comment]
How am I suppose to use it ?
Adding this to my `config/initializers/database.cr` renders logs without errors
```crystal
Log.setup("db", levels[ENV["KEMAL_ENV"]], Log::IOBackend.new(formatter: Jennifer::Adapter::DBFormatter))
```
![image](https://github.com/imdrasil/jennifer.cr/assets/75388869/cf88c4ee-6865-44c6-8931-5c5dd8d5970d)

**Comment by imdrasil** [comment]
Now Getting Started page has an example how to use new 
 
```crystal
require "jennifer/adapter/db_colorized_formatter"

Log.setup "db", :debug, Log::IOBackend.new(formatter: Jennifer::Adapter::DBColorizedFormatter)
```
