### ISSUE TITLE
Jennifer.cr is broken '-- Task not found.'

### ISSUE THREAD

**Issue by pateljoel** [imdrasil/jennifer.cr#452]
I have setup jennifier on my side and I ran into this issue when running this command from the README.

`crystal sam.cr -- generate:migration CreateContact`

```
Task -- was not found
Task -- was not found
```

Am I doing something wrong or is Jennifer broken?

**Comment by imdrasil** [comment]
Hi, I'll double check all of the places where this pattern is still present. Please use `crystal sam.cr generate:migration CreateContact` instead

**Comment by imdrasil** [comment]
I've merged the change to the docs so now it should not have this outdated pattern
