### ISSUE TITLE
Add h1 title to documentation pages

### ISSUE THREAD

**Issue by faustinoaq** [imdrasil/jennifer.cr#61]
Hi @imdrasil jennifer looks amazing!

We are using Jennifer at [Amber](https://amberframework.org/guides#getting-started/models/jennifer/README.md) too

This issue is a suggestion to add h1 title to he following pages:

- https://amberframework.org/guides#/imdrasil/jennifer.cr/master/docs/configuration.md
- https://amberframework.org/guides#/imdrasil/jennifer.cr/master/docs/migration.md
- https://amberframework.org/guides#/imdrasil/jennifer.cr/master/docs/model_mapping.md
- https://amberframework.org/guides#/imdrasil/jennifer.cr/master/docs/model_sti.md
- https://amberframework.org/guides#/imdrasil/jennifer.cr/master/docs/callbacks.md
- https://amberframework.org/guides#/imdrasil/jennifer.cr/master/docs/validation.md
- https://amberframework.org/guides#/imdrasil/jennifer.cr/master/docs/timestamps.md
- https://amberframework.org/guides#/imdrasil/jennifer.cr/master/docs/relations.md
- https://amberframework.org/guides#/imdrasil/jennifer.cr/master/docs/crud.md
- https://amberframework.org/guides#/imdrasil/jennifer.cr/master/docs/query_dsl.md
- https://amberframework.org/guides#/imdrasil/jennifer.cr/master/docs/eager_loading.md
- https://amberframework.org/guides#/imdrasil/jennifer.cr/master/docs/pagination_and_ordering.md
- https://amberframework.org/guides#/imdrasil/jennifer.cr/master/docs/model_scopes.md
- https://amberframework.org/guides#/imdrasil/jennifer.cr/master/docs/aggregation.md
- https://amberframework.org/guides#/imdrasil/jennifer.cr/master/docs/transaction_and_lock.md

I wrongly added a copyright message to bottom page, maybe I can delete this message or replace it with a new one 😅 

![screenshot_20171013_215309](https://user-images.githubusercontent.com/3067335/31571901-e8d873d0-b060-11e7-86b5-d63736755720.png)

Thanks you for jennifer!

**Comment by imdrasil** [comment]
@faustinoaq done. About "copyright" - actually this lib is under the MIT license so I can asa you to switch only to "copyleft" but I'm not sure for proper format ) will think about it and ping you

**Comment by faustinoaq** [comment]
@eliasjpr @elorest @drujensen WDYT about copyright message on amber guides footer ?

Maybe can we use some Creative Common License for documentation ?
