### ISSUE TITLE
macro def error on Crystal 0.23.0+266 [51bf36933] (2017-10-16)

### ISSUE THREAD

**Issue by russ** [imdrasil/jennifer.cr#63]
Getting this error when running my code against the latest version.

```
require "jennifer"
^

in lib/jennifer/src/jennifer.cr:20: while requiring "./jennifer/model/*"

require "./jennifer/model/*"
^

Syntax error in lib/jennifer/src/jennifer/model/base.cr:155: unexpected token: self (parentheses are mandatory for macro arguments)

      macro def self.models
                ^
```

I think it's related to this change. https://github.com/crystal-lang/crystal/pull/5043

**Comment by imdrasil** [comment]
@russ crystal 0.23.0 version is very buggy in term of inheriting macroses. Please update to latest version (now it is 0.23.1) - everything should work fine.

**Comment by imdrasil** [comment]
for now I close it. fill free to reopen if will face with same problem with 0.23.1 version

**Comment by lipanski** [comment]
The Crystal version that @russ is mentioning is actually the 0.24 pre-release. I tried to fix the breaking changes with https://github.com/imdrasil/jennifer.cr/pull/84
