### ISSUE TITLE
No target defs

### ISSUE THREAD

**Issue by Xosmond** [imdrasil/jennifer.cr#67]
Im getting this error:

```
Error in lib/jennifer/src/jennifer/adapter/base_sql_generator.cr:137: BUG: no target defs

          io << query._raw_select
```

 When I run this command on a amber project:

`crystal src/sam.cr -- generate:migration CreateCompanies`

Any idea on whats the problem?

**Comment by z64** [comment]
Could you provide some of your environment details? Namely crystal version (`crystal -v`), version of jennifer (`shards list`), and what DB config you are using?

**Comment by imdrasil** [comment]
@Xosmond @z64 yeah, I know the reason. somewhy sometimes (I can't find minimal code that will reproduce this bug) method which returns `T?` (for any T) and result is used for `StringBuilder` you can face with such issue

**Comment by imdrasil** [comment]
@Xosmond Today will commit a fix to the master.

**Comment by Xosmond** [comment]
Heres the information (running on a MacOS 10.12.6):
Crystal version: Crystal 0.23.1 (2017-10-12) LLVM 4.0.1
Jennifer version 0.4.0 (while shards list show 0.3.4)

Oh great @imdrasil, I will wait for it then. Thank you for taking care of it. I hope I can learn more crystal to contribute to Jennifer on the future.

**Comment by imdrasil** [comment]
@Xosmond try to pull from master branch actually it already should be fixed

**Comment by Xosmond** [comment]
@imdrasil Yes, you are right, with master branch it works fine. Now I can close this. Good job, Regards.

**Comment by imdrasil** [comment]
@Xosmond in few hours I will make new release (`0.4.1`) so u can switch to normal specifying in shards file

**Comment by Xosmond** [comment]
@imdrasil Sr, I have some questions about validations (the way is implemented), where can I talk about it?

**Comment by imdrasil** [comment]
@Xosmond via email (u can find it in my profile). Or if u think that conversation is important or can help someone - create an issue
