### ISSUE TITLE
Issues after updating to 0.4.1

### ISSUE THREAD

**Issue by Ethreal** [imdrasil/jennifer.cr#71]
I found at least two:
1.  `has_many :stats, Stats` in Model gives me an error
`in macro 'has_many' expanded macro: included:1, line 6:
type must be NoReturn, not Stats:Class`

2. While using `sam` i.e. `crystal sam.cr -- db:schema:load` Config.db returns "" nevetherless db is in config for sure, during `def self.read` db is set properly, but is gone somewhere after.

Rolling back to 0.4.0 all the errors are gone.

**Comment by imdrasil** [comment]
@Ethreal paste please simple code which helps to reproduce 1)

**Comment by Ethreal** [comment]
Model1
```
require "pg"
require "jennifer/adapter/postgres"
require "jennifer"
require "../models/jennifer"

class Links < Jennifer::Model::Base
  with_timestamps
  mapping(
    id: {type: Int32, primary: true},
    ...
    created_at: {type: Time, null: true},
    updated_at: {type: Time, null: true}
  )

  has_many :stats, Stats
```

Model2
```
require "pg"
require "jennifer/adapter/postgres"
require "jennifer"
require "../models/jennifer"

class Stats < Jennifer::Model::Base
  with_timestamps
  mapping(
    id: {type: Int32, primary: true},
    links_id: {type: Int32, null: false},
    created_at: {type: Time, null: true},
    updated_at: {type: Time, null: true}
  )

  belongs_to :link, Links, foreign: "links_id"
```

Hope it helps

**Comment by imdrasil** [comment]
@Ethreal can't reproduce anyway :( - please find minimum amount of code which reproduce both issues (at once or separately) and paste here or create a repo with it.

**Comment by imdrasil** [comment]
@Ethreal , did you have a chance to find out smth on this?

**Comment by Ethreal** [comment]
Sorry, a bit overwhelmed now, as it works fine with 0.4.0 I stopped to investigate further, I'll try to add context during a week.

**Comment by imdrasil** [comment]
thanks for your help ;-)

**Comment by zauner** [comment]
Hi, I have the same problem with the `has_many` relation. I did not use any older version though, so I can't tell if that code would have worked before.

```Crystal
class Foo < Jennifer::Model::Base
  
  mapping(
    id: {type: Int64, primary: true},
    parent_id: Int64?
  )
  
  has_many :bars, Bar

end

class Bar < Jennifer::Model::Base
 
 mapping(
   id: {type: Int64, primary: true},
   foo_id: Int64,
   value: String
 )

end
```

gives me `type must be NoReturn, not Bar:Class` at

```
in macro 'has_many' expanded macro: included:1, line 6:

   1.
   2.
   3.           ::Jennifer::Model::RelationDefinition.declare_dependent(:bars, :nullify, :has_many)
   4.
   5.           @@relations["bars"] =
>  6.             ::Jennifer::Relation::HasMany(Bar, Foo).new("bars", nil, nil,
   7.               Bar.all)
   8.
   9.
```
The same goes for a `belongs_to` in the other direction.

I tried to dig into it, but am pretty new to Crystal. As far as I can tell it already blows up when reaching the Generic `::Jennifer::Relation::HasMany(Bar, Foo)`.

**Comment by imdrasil** [comment]
@zauner which crystal version are u using? And try please master latest commit if it helps with this problem

**Comment by zauner** [comment]
Alright, I just tried with the latest master, but that did not help. Crystal version is

Crystal 0.23.1 [e2a1389] (2017-07-13) LLVM 3.8.1

from the Debian package.

**Comment by imdrasil** [comment]
@zauner would you mind to prepare paste-n-run code example, because given code snippet runs normally on master.

**Comment by zauner** [comment]
Hm, I extracted the code in a separate project with only jennifer as dependency and you are right, it works there.

However, I am getting that error when running within the Amber framework. Are there maybe any best practices on how to integrate jennifer with Amber that I am missing?

**Comment by imdrasil** [comment]
For now we have no designed best practices. Would you mind to make repo with your amber configuration which reproduces this error - I would like to investigate such kind of issue.

**Comment by zauner** [comment]
I figured it out. I required the model code _after_ the controller code, which is using the models. Makes sense, that this does not work, just strange that this result in such an error message.

Nevertheless, thanks for pushing me into the right direction :)

**Comment by imdrasil** [comment]
@Ethreal please check if found upper solution fits your issue

**Comment by imdrasil** [comment]
If proposed solution doesn't fit your issue with latest master - feel free to reopen this one

**Comment by imdrasil** [comment]
Faced with "type must be NoReturn, not Stats.class" one more time - when using `minitest` (in spec mode). Resolved by moving `require"minitest/autorun"` after models definition. Still curious what is the exact reason for such kind of behaviour.
