### ISSUE TITLE
Wrong number of arguments for 'Mode.new' (given 0, expected 1..2)

### ISSUE THREAD

**Issue by Xosmond** [imdrasil/jennifer.cr#73]
Where is new definition called from this method?

https://github.com/imdrasil/jennifer.cr/blob/b9194fef9c894e4b2e31825a77131c0cf0e63ad1/src/jennifer/model/base.cr#L97

Getting this error when I try to build an empty object: (Company is my Model)

```
in lib/jennifer/src/jennifer/model/base.cr:97: wrong number of arguments for 'Company.new' (given 0, expected 1..2)
Overloads are:
 - Company.new(values : Hash | NamedTuple, new_record)
 - Company.new(__temp_88 : DB::ResultSet)
 - Company.new(values : Hash(Symbol, ::Jennifer::DBAny) | NamedTuple)
 - Company.new(values : Hash(String, ::Jennifer::DBAny))
```

**Comment by imdrasil** [comment]
Missed this important update - not all models could be created without any arguments. If your model has at least one non nil field - you will have no default (without arguments) constructor (and `#build` method after the fix).

**Comment by imdrasil** [comment]
master has fix for this one

**Comment by Xosmond** [comment]
I understand so I should create new forms without an object. By the way, I think It should be able to create objects and then validate just when is going to be saved, like ActiveRecord. The also means to create an validate_presence_of and so on.

Or there is a problem with that?

**Comment by imdrasil** [comment]
interesting thought. In this case all fields should be nillable (on the crystal side) by default. Or (which is acceptable variant, as for me) validate on compile time if declared field is nillable or has default value (to be initialized with default constructor), in the other case - compile time exception will be raised

**Comment by imdrasil** [comment]
@Xosmond actually now it already works in such way - if will attributes are primary key, nillable or with default value - default constructor will be defined. If

**Comment by Xosmond** [comment]
But if I make all my fields nillable on the mapping of the model, how can I validate presence of the fields when is going to be saved?
Because on DB the fields are not nillable.

**Comment by imdrasil** [comment]
@Xosmond my point was that we declare some type for field and should respect it during object building (if our field can't be null in the db - it shouldn't in crystal as well). but your point is interesting as well

**Comment by Xosmond** [comment]
I think would be better to let programmer decide, because I some cases people need empty objects or they need to build them field by field and other situations.

We need to have independency of the database but be sure to have correct models.

Well, I think other people should say what they think. By now, I closed this issue.

**Comment by imdrasil** [comment]
@Xosmond but I think Jennifer provide enough Independence - you are able to define a type you wish (nillable, with default value). If you want to restrict from creating object with empty values - define nonnillable type or add default value. If someone think this (making all model attributes nilable) is important - create separate issue to discuss.
