### ISSUE TITLE
`migration:generate` should be `generate:migration` in the README

### ISSUE THREAD

**Issue by faultyserver** [imdrasil/jennifer.cr#8]
I'm just getting started with `jennifer.cr` and was trying to get my database up and running for my application. After running `db:create`, I was ready to create a migration, so I looked at the README for instructions. It says to run

```bash
$ crystal sam.cr -- migration:generate your_migration_name
```

but doing so returns a "Task migration:generate was not found" exception.

Looking at [the source](https://github.com/imdrasil/jennifer.cr/blob/master/src/jennifer/sam.cr#L32), it looks like the task name is actually `generate:migration`, and running that command seems to work:

```bash
$ crystal sam.cr -- generate:migration create_users
Migration CreateUsers20170512222213819 was generated
$
```

**Comment by imdrasil** [comment]
thanks for helping )
